"""Abstract base class for all synthetic, local-first workload generators."""

from __future__ import annotations

import abc
import logging
import os
import signal
import subprocess

from lab.agent.operations.runner import SystemRunner
from lab.workloads.models import WorkloadClass, WorkloadExecutionResult, WorkloadProfile

logger = logging.getLogger(__name__)


class WorkloadGenerator(abc.ABC):
    """Base class for reproducible, unprivileged, process-owned application traffic generators."""

    def __init__(
        self,
        profile: WorkloadProfile,
        runner: SystemRunner | None = None,
    ) -> None:
        self.profile = profile
        self.profile.validate_safety()
        self.runner = runner or SystemRunner()
        self.server_proc: subprocess.Popen[bytes] | None = None
        self.server_pid: int | None = None
        self.client_pid: int | None = None

    @property
    @abc.abstractmethod
    def workload_class(self) -> WorkloadClass:
        """The application category generated by this subclass."""
        ...

    @abc.abstractmethod
    def start_server(
        self,
        server_netns: str,
        bind_ip: str,
        port: int,
    ) -> None:
        """Start local sink / server process in target namespace with tracked PID."""
        ...

    @abc.abstractmethod
    def run_client(
        self,
        client_netns: str,
        target_ip: str,
        target_port: int,
        duration_seconds: float,
        seed: int,
    ) -> WorkloadExecutionResult:
        """Execute client traffic generation against target server inside client namespace."""
        ...

    def stop_server(self) -> None:
        """Terminate the server process owned by this generator."""
        if self.server_proc is not None:
            logger.debug("Terminating server PID %d", self.server_proc.pid)
            try:
                self.server_proc.terminate()
                self.server_proc.wait(timeout=2.0)
            except (subprocess.TimeoutExpired, ProcessLookupError):
                try:
                    self.server_proc.kill()
                    self.server_proc.wait(timeout=1.0)
                except (OSError, subprocess.SubprocessError) as exc:
                    logger.debug("Error while killing server process: %s", exc)
            finally:
                self.server_proc = None
                self.server_pid = None

        if self.server_pid is not None:
            # Fallback for background process tracked via PID
            try:
                os.kill(self.server_pid, signal.SIGTERM)
            except (ProcessLookupError, PermissionError):
                pass
            self.server_pid = None

    def clean_up(self) -> None:
        """Ensure all owned generator processes are cleaned up."""
        self.stop_server()
