"use client";
import React from "react";
import { AlertTriangle } from "lucide-react";
import { formatCoverage } from "@/lib/format";
import { useCountUp } from "@/lib/motion";
export interface ScoreDisplayProps { score: number | null | undefined; coverage?: number | null | undefined; riskTier?: string | null | undefined; status?: string | null | undefined; size?: "sm" | "md" | "lg"; showCoverage?: boolean; className?: string; }
export function isScoreAssessable(score: number | null | undefined, coverage?: number | null | undefined, status?: string | null | undefined, riskTier?: string | null | undefined): boolean { if (score == null || status === "INSUFFICIENT_EVIDENCE" || status === "NOT_ASSESSABLE" || riskTier === "INSUFFICIENT_EVIDENCE") return false; if (coverage != null && (coverage <= 1 ? coverage * 100 : coverage) < 60) return false; return true; }
export function ScoreDisplay({ score, coverage, riskTier, status, size = "md", showCoverage = false, className = "" }: ScoreDisplayProps) {
  const assessable = isScoreAssessable(score, coverage, status, riskTier); const cov = coverage == null ? null : (coverage <= 1 ? coverage * 100 : coverage); const resolved = assessable ? Number(score) : null; const count = useCountUp(size === "lg" ? resolved : null, { duration: 900 }); const color = Number(score) < 60 ? "text-critical" : Number(score) >= 80 ? "text-positive" : "text-ink";
  if (!assessable) return size === "sm" ? <span className={`inline-flex items-center gap-1.5 text-xs font-mono text-medium ${className}`}><AlertTriangle className="h-3.5 w-3.5" />{cov && cov > 0 ? "PARTIAL" : "NOT ASSESSABLE"}{cov !== null && <small className="text-ink-3"> · {formatCoverage(coverage)} evidence</small>}</span> : <div className={`flex items-start gap-3 ${className}`}><AlertTriangle className="mt-1 h-5 w-5 shrink-0 text-medium" /><div><p className="editorial-title text-2xl">NOT ASSESSABLE</p><p className="mt-1 max-w-[54ch] text-xs leading-5 text-ink-2">{cov === 0 || cov === null ? "No assessable IPsec packet evidence was found. Score withheld." : `Evidence coverage is ${formatCoverage(coverage)}; the required 60% threshold was not met. Score withheld.`}</p></div></div>;
  if (size === "sm") return <span className={`font-mono text-sm font-medium tabular-nums ${color} ${className}`}>{Number(score).toFixed(0)}<span className="ml-1 text-xs text-ink-3">/100</span></span>;
  return <div className={`flex items-baseline gap-2 ${className}`}><span className={`editorial-title tabular-nums ${size === "lg" ? "text-7xl sm:text-8xl" : "text-4xl"} ${color}`}>{size === "lg" ? count : Number(score).toFixed(0)}</span><span className="font-mono text-xs text-ink-3">/ 100</span>{showCoverage && cov !== null && <span className="ml-2 text-xs text-ink-3">{formatCoverage(coverage)} evidence</span>}</div>;
}
export function renderScore(score: number | null | undefined, coverage?: number | null | undefined, riskTier?: string | null | undefined, size: "sm" | "md" | "lg" = "md") { return <ScoreDisplay score={score} coverage={coverage} riskTier={riskTier} size={size} />; }
