"use client";
import React, { useState } from "react";
import { Check, Copy } from "lucide-react";
export function CopyableValue({ value, label, truncate = false }: { value: string; label?: string; truncate?: boolean }) { const [copied, setCopied] = useState(false); const display = truncate && value.length > 16 ? `${value.slice(0, 8)}…${value.slice(-8)}` : value; const copy = async (event: React.MouseEvent) => { event.stopPropagation(); try { await navigator.clipboard.writeText(value); setCopied(true); window.setTimeout(() => setCopied(false), 1800); } catch { setCopied(false); } }; return <span className="inline-flex items-center gap-1.5 font-mono text-xs text-ink-2"><span title={value}>{display}</span><button type="button" onClick={copy} className="p-1 text-ink-3 hover:text-ink" title={label ? `Copy ${label}` : "Copy value"} aria-label={label ? `Copy ${label}` : "Copy value"}>{copied ? <Check className="h-3.5 w-3.5 text-positive" /> : <Copy className="h-3.5 w-3.5" />}</button></span>; }
export function Table({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <div className={`w-full overflow-x-auto ${className}`}><table className="w-full border-collapse text-left text-[13px]">{children}</table></div>; }
export function TableHeader({ children }: { children: React.ReactNode }) { return <thead className="border-b border-line text-left text-[.66rem] uppercase tracking-[.09em] text-ink-3">{children}</thead>; }
export function TableBody({ children }: { children: React.ReactNode }) { return <tbody className="divide-y divide-line">{children}</tbody>; }
export function TableRow({ children, onClick, isSelected = false, className = "" }: { children: React.ReactNode; onClick?: () => void; isSelected?: boolean; className?: string }) { return <tr onClick={onClick} onKeyDown={onClick ? (e) => { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); onClick(); } } : undefined} tabIndex={onClick ? 0 : undefined} className={`${isSelected ? "bg-accent-soft" : "hover:bg-white/40"} transition-colors ${onClick ? "cursor-pointer focus-visible:outline" : ""} ${className}`}>{children}</tr>; }
export function TableCell({ children, className = "", mono = false, colSpan }: { children: React.ReactNode; className?: string; mono?: boolean; colSpan?: number }) { return <td colSpan={colSpan} className={`px-2 py-3 align-middle text-ink-2 sm:px-3 ${mono ? "font-mono text-xs tabular-nums" : ""} ${className}`}>{children}</td>; }
export function TableHead({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <th className={`px-2 py-3 font-medium sm:px-3 ${className}`}>{children}</th>; }
